const apps = [
    // SALUD
    { id: 'S01', category: 'SALUD', name: 'Chat Diagnóstico SMS', desc: 'Diagnóstico básico por SMS/WhatsApp.' },
    { id: 'S02', category: 'SALUD', name: 'First Aid Offline', desc: 'App de primeros auxilios offline.' },
    { id: 'S03', category: 'SALUD', name: 'CardioCam PPG', desc: 'Monitor cardíaco por cámara (PPG).' },
    { id: 'S04', category: 'SALUD', name: 'Vocal Stress Detector', desc: 'Detector de estrés vía micrófono.' },
    { id: 'S05', category: 'SALUD', name: 'Meds Control Mini', desc: 'Control de medicamentos con alertas.' },
    { id: 'S06', category: 'SALUD', name: 'Telemed Lite', desc: 'Telemedicina ultraliviana sin video.' },
    { id: 'S07', category: 'SALUD', name: 'Mental Breath', desc: 'Salud mental con ejercicios guiados.' },
    { id: 'S08', category: 'SALUD', name: 'Dengue Tracker', desc: 'Registro de mosquitos con geotags.' },
    { id: 'S09', category: 'SALUD', name: 'Safe Birth Protocol', desc: 'Protocolo de parto seguro offline.' },
    { id: 'S10', category: 'SALUD', name: 'Symptom PDF Log', desc: 'Diario de síntomas exportable.' },
    { id: 'S11', category: 'SALUD', name: 'Senior SOS Button', desc: 'Botón de emergencia para adultos mayores.' },
    { id: 'S12', category: 'SALUD', name: 'Family MedKit', desc: 'Inventario de botiquín familiar.' },
    { id: 'S13', category: 'SALUD', name: 'Posture AI', desc: 'Medir postura con cámara.' },
    { id: 'S14', category: 'SALUD', name: 'Thermal Vision Sim', desc: 'Detector de fiebre virtual (RGB).' },
    { id: 'S15', category: 'SALUD', name: 'Rural Nutrition Guide', desc: 'Guía de nutrición para zonas rurales.' },
    { id: 'S16', category: 'SALUD', name: 'Caregiver Checklist', desc: 'Checklist para cuidadores.' },
    { id: 'S17', category: 'SALUD', name: 'Glucose Log AI', desc: 'Lectura y predicción de glucosa.' },
    { id: 'S18', category: 'SALUD', name: 'Local Medic Map', desc: 'Mapa de brigadas médicas locales.' },
    { id: 'S19', category: 'SALUD', name: 'Outbreak Alert', desc: 'Notificador de brotes comunitarios.' },
    { id: 'S20', category: 'SALUD', name: 'Water Quality AI', desc: 'Revisar calidad del agua con IA.' },

    // ECONOMIA
    { id: 'E21', category: 'ECONOMIA', name: 'Community Wallet', desc: 'Wallet ligera para pagos comunitarios.' },
    { id: 'E22', category: 'ECONOMIA', name: 'ROSCA Digital', desc: 'Tandas en app.' },
    { id: 'E23', category: 'ECONOMIA', name: 'Barter Local', desc: 'App de trueque local sin dinero.' },
    { id: 'E24', category: 'ECONOMIA', name: 'MicroJobs', desc: 'Plataforma de microempleos locales.' },
    { id: 'E25', category: 'ECONOMIA', name: 'Paper ID QR', desc: 'Registro de identidad en QR en papel.' },
    { id: 'E26', category: 'ECONOMIA', name: 'Offline POS', desc: 'Punto de venta móvil offline.' },
    { id: 'E27', category: 'ECONOMIA', name: 'Street Invoice', desc: 'Mini-facturación para informales.' },
    { id: 'E28', category: 'ECONOMIA', name: 'Vendor Income', desc: 'Control de ingresos ambulantes.' },
    { id: 'E29', category: 'ECONOMIA', name: 'Producer Market', desc: 'Marketplace local de productores.' },
    { id: 'E30', category: 'ECONOMIA', name: 'Climate MicroInsure', desc: 'Microseguros paramétricos.' },
    { id: 'E31', category: 'ECONOMIA', name: 'Trust Score', desc: 'Reputación comunitaria para comercios.' },
    { id: 'E32', category: 'ECONOMIA', name: 'Job Kiosk Offline', desc: 'Kiosco de empleo offline.' },
    { id: 'E33', category: 'ECONOMIA', name: 'Skill Up', desc: 'Capacitación laboral descargable.' },
    { id: 'E34', category: 'ECONOMIA', name: 'Finance Planner AI', desc: 'Planificador financiero básico.' },
    { id: 'E35', category: 'ECONOMIA', name: 'Group Savings', desc: 'Plataforma de ahorro grupal.' },
    { id: 'E36', category: 'ECONOMIA', name: 'Pre-SAT Lite', desc: 'Pre-facturador fiscal ultraliviano.' },
    { id: 'E37', category: 'ECONOMIA', name: 'Biz Dashboard', desc: 'Analítica simple para pequeños negocios.' },
    { id: 'E38', category: 'ECONOMIA', name: 'Social QR Aid', desc: 'Distribución de ayuda vía QR.' },
    { id: 'E39', category: 'ECONOMIA', name: 'Micro ERP', desc: 'ERP para microtiendas.' },
    { id: 'E40', category: 'ECONOMIA', name: 'Debt Manager', desc: 'Administrar deudas comunitarias.' },

    // EDUCACION
    { id: 'L41', category: 'EDUCACION', name: 'Offline Library', desc: 'Biblioteca digital offline.' },
    { id: 'L42', category: 'EDUCACION', name: 'Trade Sim', desc: 'Simulador de oficios.' },
    { id: 'L43', category: 'EDUCACION', name: 'Zero to Read', desc: 'Aprender a leer/escribir.' },
    { id: 'L44', category: 'EDUCACION', name: 'Pocket Lab', desc: 'Laboratorio de ciencia con cámara.' },
    { id: 'L45', category: 'EDUCACION', name: 'Micro Skills', desc: 'Habilidades laborales en microlecciones.' },
    { id: 'L46', category: 'EDUCACION', name: 'Local Guitar', desc: 'Aprender guitarra sin streaming.' },
    { id: 'L47', category: 'EDUCACION', name: 'Visual Dictionary', desc: 'Diccionario para alfabetización.' },
    { id: 'L48', category: 'EDUCACION', name: 'Homework Helper', desc: 'Guías de tareas sin internet.' },
    { id: 'L49', category: 'EDUCACION', name: 'Brain Trainer', desc: 'Entrenador de memoria y cognición.' },
    { id: 'L50', category: 'EDUCACION', name: 'Rural School Agenda', desc: 'Agenda digital para escuelas.' },
    { id: 'L51', category: 'EDUCACION', name: 'Math Photo Tutor', desc: 'Tutor de matemáticas por foto.' },
    { id: 'L52', category: 'EDUCACION', name: 'School Map', desc: 'Mapa escolar comunitario.' },
    { id: 'L53', category: 'EDUCACION', name: 'Kids Storyteller', desc: 'App de storytelling para niños.' },
    { id: 'L54', category: 'EDUCACION', name: 'Chem Sim Safe', desc: 'Simulador de laboratorio químico.' },
    { id: 'L55', category: 'EDUCACION', name: 'Long Text Reader', desc: 'Lectura de textos largos.' },
    { id: 'L56', category: 'EDUCACION', name: 'Agro Course', desc: 'Cursos de agricultura sostenible.' },
    { id: 'L57', category: 'EDUCACION', name: 'Retention Tool', desc: 'App de retención escolar.' },
    { id: 'L58', category: 'EDUCACION', name: 'Tradition Wiki', desc: 'Enciclopedia de oficios tradicionales.' },
    { id: 'L59', category: 'EDUCACION', name: 'Finance 101', desc: 'Clases de finanzas personales.' },
    { id: 'L60', category: 'EDUCACION', name: 'First Tech', desc: 'Enseñar a usar tecnología.' },

    // INFRAESTRUCTURA
    { id: 'I61', category: 'INFRAESTRUCTURA', name: 'Risk Map', desc: 'Mapa comunitario de riesgos.' },
    { id: 'I62', category: 'INFRAESTRUCTURA', name: 'Service Report', desc: 'Reportar fallas en servicios.' },
    { id: 'I63', category: 'INFRAESTRUCTURA', name: 'Volunteer Geo', desc: 'Voluntariado con geolocalización.' },
    { id: 'I64', category: 'INFRAESTRUCTURA', name: 'Shelter Manager', desc: 'Gestor de refugios temporales.' },
    { id: 'I65', category: 'INFRAESTRUCTURA', name: 'Trash Log', desc: 'Registro de basura y reciclaje.' },
    { id: 'I66', category: 'INFRAESTRUCTURA', name: 'Quake Alert Crowd', desc: 'Alertas sísmicas locales.' },
    { id: 'I67', category: 'INFRAESTRUCTURA', name: 'Water Truck Map', desc: 'Mapa de agua potable y pipas.' },
    { id: 'I68', category: 'INFRAESTRUCTURA', name: 'Energy Dash', desc: 'Dashboard de energía comunitaria.' },
    { id: 'I69', category: 'INFRAESTRUCTURA', name: 'Tool Share', desc: 'Compartir herramientas vecinales.' },
    { id: 'I70', category: 'INFRAESTRUCTURA', name: 'Verified Trades', desc: 'Directorio de oficios verificados.' },
    { id: 'I71', category: 'INFRAESTRUCTURA', name: 'Transport Coord', desc: 'Coordinación de transporte.' },
    { id: 'I72', category: 'INFRAESTRUCTURA', name: 'Food Bank Inv', desc: 'Inventario de bancos de alimentos.' },
    { id: 'I73', category: 'INFRAESTRUCTURA', name: 'Brigade Route', desc: 'Ruteo óptimo de brigadas.' },
    { id: 'I74', category: 'INFRAESTRUCTURA', name: 'Animal Registry', desc: 'Registro de animales comunitarios.' },
    { id: 'I75', category: 'INFRAESTRUCTURA', name: 'Home Repair Manual', desc: 'Manual de reparaciones básicas.' },
    { id: 'I76', category: 'INFRAESTRUCTURA', name: 'Energy Audit', desc: 'Inventario energético familiar.' },
    { id: 'I77', category: 'INFRAESTRUCTURA', name: 'Street Quality AI', desc: 'Evaluar calidad de calles.' },
    { id: 'I78', category: 'INFRAESTRUCTURA', name: 'Trash Route DIY', desc: 'Ruteo de basura informal.' },
    { id: 'I79', category: 'INFRAESTRUCTURA', name: 'Infra DIY Guide', desc: 'Guía para construir infraestructura.' },
    { id: 'I80', category: 'INFRAESTRUCTURA', name: 'Community News CMS', desc: 'Mini CMS para periodismo.' },

    // JUSTICIA
    { id: 'J81', category: 'JUSTICIA', name: 'Panic Button Enc', desc: 'Botón de pánico cifrado.' },
    { id: 'J82', category: 'JUSTICIA', name: 'Forensic Lens', desc: 'Evidencia forense con metadatos.' },
    { id: 'J83', category: 'JUSTICIA', name: 'Legal AI Drafter', desc: 'IA para redactar documentos.' },
    { id: 'J84', category: 'JUSTICIA', name: 'Bureaucracy Translator', desc: 'Traductor de trámites.' },
    { id: 'J85', category: 'JUSTICIA', name: 'Asset QR Log', desc: 'Registro de bienes por QR.' },
    { id: 'J86', category: 'JUSTICIA', name: 'Missing Persons Protocol', desc: 'Acompañamiento para desaparecidos.' },
    { id: 'J87', category: 'JUSTICIA', name: 'Safe Report', desc: 'Reporte anónimo de abuso.' },
    { id: 'J88', category: 'JUSTICIA', name: 'Doc Verifier', desc: 'Verificador de autenticidad.' },
    { id: 'J89', category: 'JUSTICIA', name: 'Land Hash', desc: 'Registro de tierras en blockchain.' },
    { id: 'J90', category: 'JUSTICIA', name: 'Digital Wallet Docs', desc: 'Cartera de documentos personales.' },
    { id: 'J91', category: 'JUSTICIA', name: 'Extortion Alert', desc: 'Notificador de extorsión.' },
    { id: 'J92', category: 'JUSTICIA', name: 'Simple Law', desc: 'Leyes locales en lenguaje simple.' },
    { id: 'J93', category: 'JUSTICIA', name: 'Portable File', desc: 'Expediente digital portátil.' },
    { id: 'J94', category: 'JUSTICIA', name: 'Conciliation Center', desc: 'Centro de conciliación digital.' },
    { id: 'J95', category: 'JUSTICIA', name: 'Detention Cam', desc: 'Grabar detenciones con respaldo.' },
    { id: 'J96', category: 'JUSTICIA', name: 'Family Legal Log', desc: 'Bitácora legal familiar.' },
    { id: 'J97', category: 'JUSTICIA', name: 'Danger Map Night', desc: 'Mapa de puntos inseguros.' },
    { id: 'J98', category: 'JUSTICIA', name: 'Migration Assist', desc: 'Asistente trámites migratorios.' },
    { id: 'J99', category: 'JUSTICIA', name: 'Legal Sim', desc: 'Simulador legal de qué hacer.' },
    { id: 'J100', category: 'JUSTICIA', name: 'Police Protocol Check', desc: 'Verificar abusos policiales.' }
];

module.exports = apps;
